project_id = "zhgwhsrhrfsjdupikobo"

[api]
enabled = true

[db]
major_version = 17

[studio]
enabled = true

[auth]
enabled = true
site_url = "https://pm.w-software.net"
additional_redirect_urls = ["http://localhost:8000", "http://127.0.0.1:8000"]

[auth.mfa]
max_enrolled_factors = 10

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[auth.email]
enable_signup = false
enable_confirmations = true
max_frequency = "1m0s"
otp_length = 8

[storage]
enabled = true
